### ISSUE TITLE
Can we download Value mappings with this plugin

### ISSUE THREAD

**Issue by Srinu3366** [figaf/cpi-gradle-plugin#14]
I am using this plugin to version control my integration flow artifacts. Getting an error while trying to download value mappings.

Is it possible to download value mappings using this plugin?

**Comment by dgraversen** [comment]
Hi 
Value mappings are not supported, at the moment. 
In the Figaf Tool we do have the option to version value mappings. They are also automatically synchronized to the git repository. But for now it has not been as action-oriented, it has just been version only. 
We will check if it is possible. 
Daniel

**Comment by Srinu3366** [comment]
Thanks for making these plugins open source.

I am closing this issue now as it is not a bug but more of a question.

**Comment by dgraversen** [comment]
Hi 
We are currently adding working on this feature.

**Comment by dgraversen** [comment]
Value mappings is now also possible with latest release
