### ISSUE TITLE
Upgrade to 2.0.RELEASE causing error

### ISSUE THREAD

**Issue by Srinu3366** [figaf/cpi-gradle-plugin#30]
I am trying to upgrade to version 2.0 or higher but getting an error. 

Execution failed for task ':TractToMaximoIntegration:iflow-Trigger_Track_TimeSheets_Processing:uploadArtifact'.
> com.figaf.integration.common.exception.ClientIntegrationException: com.figaf.integration.common.exception.ClientIntegrationException: Error occurred while uploading value mapping: For input string: ""

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

my settings.gradle
pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}
include "TractToMaximoIntegration"
project (":TractToMaximoIntegration").projectDir = file("TractToMaximoIntegration")

include "TractToMaximoIntegration:iflow-Get_Authorized_Time_and_Costs_from_Track"
project (":TractToMaximoIntegration:iflow-Get_Authorized_Time_and_Costs_from_Track").projectDir = file("TractToMaximoIntegration/Get_Authorized_Time_and_Costs_from_Track")

include "TractToMaximoIntegration:iflow-Maximo_PO_Number_Lookup"
project (":TractToMaximoIntegration:iflow-Maximo_PO_Number_Lookup").projectDir = file("TractToMaximoIntegration/Maximo_PO_Number_Lookup")

include "TractToMaximoIntegration:iflow-Process_Time_Sheets_Status_To_Track"
project (":TractToMaximoIntegration:iflow-Process_Time_Sheets_Status_To_Track").projectDir = file("TractToMaximoIntegration/Process_Time_Sheets_Status_To_Track")

include "TractToMaximoIntegration:iflow-Process_Track_Sheets_to_Maximo"
project (":TractToMaximoIntegration:iflow-Process_Track_Sheets_to_Maximo").projectDir = file("TractToMaximoIntegration/Process_Track_Sheets_to_Maximo")

include "TractToMaximoIntegration:iflow-Set_Time_and_Costs_Export_Status_to_Sent"
project (":TractToMaximoIntegration:iflow-Set_Time_and_Costs_Export_Status_to_Sent").projectDir = file("TractToMaximoIntegration/Set_Time_and_Costs_Export_Status_to_Sent")

include "TractToMaximoIntegration:iflow-Trigger_Track_TimeSheets_Processing"
project (":TractToMaximoIntegration:iflow-Trigger_Track_TimeSheets_Processing").projectDir = file("TractToMaximoIntegration/Trigger_Track_TimeSheets_Processing")

include "TractToMaximoIntegration:iflow-Process_Track_Sheets_to_McPherson"
project (":TractToMaximoIntegration:iflow-Process_Track_Sheets_to_McPherson").projectDir = file("TractToMaximoIntegration/Process_Track_Sheets_to_McPherson")

my build.gradle
buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

plugins {
    id 'groovy'
    id 'java'
    id 'com.figaf.cpi-plugin' version '2.0.RELEASE' apply false
}

configure(subprojects.findAll()) { sub ->

    apply plugin: 'idea'
    apply plugin: 'groovy'

    repositories {
        mavenLocal()
        jcenter()
    }

    if (sub.name.startsWith("iflow-")) {
        apply plugin: 'com.figaf.cpi-plugin'

        cpiPlugin {
            url = cpiUrl
            username = cpiUsername
            password = cpiPassword
            platformType = cloudPlatformType
            waitForStartup = true
            sourceFilePath = "$project.projectDir".toString()
            uploadDraftVersion = true
            artifactType = "CPI_IFLOW"
        }

    } else if (sub.name.startsWith("vm-")) {

        apply plugin: 'com.figaf.cpi-plugin'

        cpiPlugin {
            url = cpiUrl
            username = cpiUsername
            password = cpiPassword
            platformType = cloudPlatformType
            waitForStartup = true
            sourceFilePath = "$project.projectDir".toString()
            uploadDraftVersion = true
            artifactType = "VALUE_MAPPING"
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.5.12'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.12'
}

**Comment by dgraversen** [comment]
Hi
It is because you should use :443 in the url. We have fixed the bug in the
latest release
Daniel

**Comment by dgraversen** [comment]
Please try to upgrade to latest version or add :443 in the URL in the settings file.
